# Generated by Django 5.2 on 2025-06-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_status_alter_articlestock_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialnumber',
            name='serial_status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponible'), ('IN_USE', 'En uso'), ('UNAVAILABLE', 'No disponible'), ('IN_REPAIR', 'En reparación'), ('DAMAGED', 'Dañado'), ('LOST', 'Perdido'), ('DECOMMISSIONED', 'Dado de baja'), ('RESERVED', 'Reservado'), ('RETURNED', 'Devuelto'), ('STOLEN', 'Robado'), ('DEFECTIVE', 'Defectuoso'), ('UNDER_TESTING', 'En pruebas'), ('CALIBRATION', 'En calibración')], default='AVAILABLE', max_length=20),
        ),
    ]
