# Generated by Django 5.2 on 2025-06-09 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_serialnumber_serial_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialNumberHistory',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_serial_number_history', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('operation', models.CharField(max_length=100)),
                ('data', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_login_history', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.serialnumber')),
                ('user_login', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
    ]
