# Generated by Django 5.2 on 2025-06-17 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_serialnumberhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status_device',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='IN_STOCK', max_length=150),
        ),
    ]
