# Generated by Django 5.2 on 2025-05-28 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelhistory',
            old_name='new_data',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='modelhistory',
            name='old_data',
        ),
    ]
