# Generated by Django 5.2 on 2025-06-11 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfiluser',
            old_name='signal',
            new_name='signature',
        ),
    ]
