# Generated by Django 5.2 on 2025-05-28 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typeplan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typeplanhistory',
            old_name='new_data',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='typeplanhistory',
            name='old_data',
        ),
    ]
