# Generated by Django 5.2 on 2025-05-27 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chip', '0002_chiphistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chiphistory',
            old_name='new_data',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='chiphistory',
            name='old_data',
        ),
    ]
