# Generated by Django 5.2 on 2025-05-18 03:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('typeplan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_plan', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('gigabytes', models.PositiveIntegerField(default=0)),
                ('minutes', models.PositiveIntegerField(default=0)),
                ('messages', models.PositiveIntegerField(default=0)),
                ('unlimited_gigabytes', models.BooleanField(default=False)),
                ('unlimited_minutes', models.BooleanField(default=False)),
                ('unlimited_messages', models.BooleanField(default=False)),
                ('price', models.PositiveIntegerField(default=0)),
                ('status_billing', models.CharField(choices=[('PENDING', 'PENDING'), ('PAYING', 'PAYING'), ('CANCELED', 'CANCELED')], default='PENDING', max_length=150)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=150)),
                ('type_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typeplan.typeplan')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanHistory',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_plan_history', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('id_plan', models.CharField(max_length=200)),
                ('operation', models.CharField(max_length=100)),
                ('new_data', models.JSONField()),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_login_history', models.CharField(max_length=100)),
                ('type_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typeplan.typeplan')),
                ('user_login', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
    ]
