# Generated by Django 5.2 on 2025-05-19 01:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='date_cancellation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='date_hiring',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='plan',
            name='reason_cancellation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
