# Generated by Django 5.2 on 2025-05-19 01:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_plan_date_cancellation_plan_date_hiring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='date_cancellation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='date_hiring',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
