# Generated by Django 5.2 on 2025-06-18 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_alter_plan_date_hiring'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planhistory',
            old_name='new_data',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='planhistory',
            name='old_data',
        ),
        migrations.RemoveField(
            model_name='planhistory',
            name='type_plan',
        ),
    ]
