# Generated by Django 5.2 on 2025-05-30 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_rename_new_data_planhistory_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planhistory',
            name='type_plan',
        ),
    ]
