# Generated by Django 5.2 on 2025-05-09 00:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='id_brand',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=150),
        ),
        migrations.CreateModel(
            name='BrandHistory',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_brand_history', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('id_brand', models.CharField(max_length=200)),
                ('operation', models.CharField(max_length=100)),
                ('new_data', models.JSONField()),
                ('old_data', models.JSONField()),
                ('timestamp', models.DateTimeField()),
                ('user_login_history', models.CharField(max_length=100)),
                ('user_login', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
    ]
