# Generated by Django 5.2 on 2025-05-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_alter_brand_id_brand_alter_brand_status_brandhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandhistory',
            name='new_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brandhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
