# Generated by Django 5.2 on 2025-05-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_alter_brandhistory_new_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandhistory',
            name='new_data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='brandhistory',
            name='old_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
