# Generated by Django 5.2 on 2025-05-28 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0004_alter_brandhistory_new_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandhistory',
            old_name='new_data',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='brandhistory',
            name='old_data',
        ),
    ]
