# Generated by Django 5.2 on 2025-06-18 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('official', '0003_official_departament'),
        ('soporte', '0002_rename_imei_soporte_name_soporte_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(editable=False, max_length=50, unique=True)),
                ('type', models.CharField(choices=[('ENTRY', 'Entrada'), ('OUTPUT', 'Salida'), ('SUPPORT', 'Soporte')], max_length=10)),
                ('observation', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('login_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_transactions', to=settings.AUTH_USER_MODEL)),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='official_transactions', to='official.official')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupportTransaction',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('problem', models.TextField()),
                ('solution', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROCESS', 'En proceso'), ('COMPLETED', 'Completado')], default='PENDING', max_length=20)),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('login_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('type_soporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='soporte.soporte')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support_info', to='transaction.transaction')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetailTransaction',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('object_id', models.UUIDField()),
                ('amount', models.PositiveIntegerField(default=1)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='transaction.transaction')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionOutput',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('type_output', models.CharField(choices=[('DELIVERY', 'Entrega Permanente'), ('LOAN', 'Préstamo')], max_length=10)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('load_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='output_info', to='transaction.transaction')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
    ]
