# Generated by Django 5.2 on 2025-05-28 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_categoryhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryhistory',
            old_name='new_data',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='categoryhistory',
            name='old_data',
        ),
    ]
