# Generated by Django 5.2 on 2025-06-03 21:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Official',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_official', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_names', models.CharField(max_length=200)),
                ('pather_surname', models.CharField(max_length=200)),
                ('mather_surname', models.CharField(blank=True, max_length=200, null=True)),
                ('rut', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=150)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
    ]
