# Generated by Django 5.2 on 2025-06-10 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departament', '0001_initial'),
        ('official', '0002_officialhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='official',
            name='departament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departament.departament'),
        ),
    ]
