# Generated by Django 5.2 on 2025-06-10 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishment',
            name='address',
        ),
    ]
