# Generated by Django 5.2 on 2025-06-04 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
        ('subcategory', '0002_rename_new_data_subcategoryhistory_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='subcategory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='subcategory.subcategory'),
            preserve_default=False,
        ),
    ]
