# Generated by Django 5.2 on 2025-06-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soporte',
            old_name='imei',
            new_name='name',
        ),
        migrations.AddField(
            model_name='soporte',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
